name: Update Latest SecuritiesInBanFile
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '30 2 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Updated Latest HistoricalSecurityInBan CSV File
      CI_COMMIT_AUTHOR: DrJuneMoone
    steps:
    - uses: actions/checkout@v3
    # Build steps
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
    - run: python --version
    - run: python GetHistoricalSecurityInBan.py
      
    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      if: contains(fromJson('["schedule", "push", "pull_request"]'), github.event_name)
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "MooneDrJune@users.noreply.github.com"
        git add --all
        git commit --all -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
